FROM python:3.12-slim 


#COPY config/python/pip.conf /etc/pip.conf

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
    && apt-get install blender -y

WORKDIR /app
COPY . /app
RUN pip install poetry
RUN poetry install
EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]